### ISSUE TITLE
Server listens on random port (connection refused)

### ISSUE THREAD

**Issue by saki7** [Ericsson/CodeCheckerEclipsePlugin#110]
Currently this Eclipse plugin listens on random port, however it tries to store artifacts to the server on the fixed (default) port (I think it's 8001).
I think the port should be configurable in the Eclipse project setting.

https://github.com/Ericsson/CodeCheckerEclipsePlugin/blob/ccac28da40f4cf829a2f47405c4930fbce66b9dd/eclipse-plugin/service/cc.codechecker.service.api/src/main/java/cc/codechecker/api/runtime/CodecheckerServerThread.java#L21

**Comment by whisperity** [comment]
CodeChecker version `5.9` changed the behaviour on how the results are stored. (Pre-5.9, the database connection was directly created by the `check` command internally, and no `server` was needed for storing the results, only for viewing.)

The Eclipse plugin does **not**, in its current state, support this change. Please use an earlier release. Anything pre-5.9 should work, so I think [`v5.8`](https://github.com/Ericsson/codechecker/releases/tag/v5.8)  will suffice.

**Comment by saki7** [comment]
Workaround confirmed! Thanks.
