### ISSUE TITLE
parse plist files in the plugin

### ISSUE THREAD

**Issue by gyorb** [Ericsson/CodeCheckerEclipsePlugin#116]
plist parsing should be done by the plugin in java (See plist parsing exaple [here](https://github.com/SonarOpenCommunity/sonar-cxx/pull/1161/commits/37c125f01526e8283a936435ac97f13090e39070))

**Comment by Vodorok** [comment]
The first occurance of the new PlistParser is f8ad731cfe33050f8d6accbd8d58243a75c82d8c. The functionality reached its final form in. 0d773c109d8942fee1768883ce541c45a809a5b0
