### ISSUE TITLE
Development notes requirements

### ISSUE THREAD

**Issue by gyorb** [Ericsson/CodeCheckerEclipsePlugin#12]
Why is Eclipse PDT required?

**Comment by dutow** [comment]
It's required for development, if you want to develop it in Eclipse (which is a good idea).

That's why it's under 'development notes', not 'Requirments'

**Comment by gyorb** [comment]
Ok, the abbreviation is misleading here, because if I search for Eclipse PDT the first result point to PDT: Eclipse PHP Development Tools
Shouldn't this be PDE (Plug-in Development Environment)?
https://marketplace.eclipse.org/content/eclipse-pde-plug-development-environment

**Comment by dutow** [comment]
It should be, it was probably a typo in the original readme, I never remember which one is for plugin development/
