### ISSUE TITLE
Introduce GUI testing

### ISSUE THREAD

**Issue by gyorb** [Ericsson/CodeCheckerEclipsePlugin#131]
automatic GUI tests would be nice again if possible for multiple eclipse versions

**Comment by dkrupp** [comment]
Proposed tests:
Prerequisite: We have hello world C project in eclipse.
0. Empty codechecker config (global and local)
1. Add nature. Error message appears that codechecker needs to be configured.
2. Codechecker configuration is given.
3. build is called for hello world. Expected result: File and project level warnings appear.
