### ISSUE TITLE
EnvironmentParser test cleanup

### ISSUE THREAD

**Issue by gyorb** [Ericsson/CodeCheckerEclipsePlugin#137]
use English words in the Environment parser tests

https://github.com/Ericsson/CodeCheckerEclipsePlugin/blob/7fa3007259a879e671a1148bb1c083482f2cac82/eclipse-plugin/eclipse/cc.codechecker.eclipse.plugin.tests/src/cc/codechecker/plugin/runtime/EnvironmentParserTest.java#L16-L30

**Comment by Vodorok** [comment]
The environment parser was phased out in #170
