### ISSUE TITLE
Pictures in How to use

### ISSUE THREAD

**Issue by gyorb** [Ericsson/CodeCheckerEclipsePlugin#14]
It would be nice to have pictures about the basic setup and usage (CDT project, selecting perspective ...)

**Comment by Locutus18** [comment]
![per](https://cloud.githubusercontent.com/assets/6527692/16617496/52f4c516-4384-11e6-983c-7d9616e41e8b.png)
![perspective](https://cloud.githubusercontent.com/assets/6527692/16617502/56d97c58-4384-11e6-85e3-036ccadb0a79.png)
![config2](https://cloud.githubusercontent.com/assets/6527692/16617512/62a9a5b2-4384-11e6-891f-c71f75fb85ec.png)
![nature](https://cloud.githubusercontent.com/assets/6527692/16617515/64a7c2b8-4384-11e6-8b6a-e972c5dc3362.png)
![example](https://cloud.githubusercontent.com/assets/6527692/16617518/69013bf0-4384-11e6-9fb8-4c70157ce6aa.png)

These are good?

**Comment by gyorb** [comment]
Seems good to me.

**Comment by dutow** [comment]
The add nature picture is too big, it isn't readable in a smaller size, and at least 2/3 of the image is unnecessary.

**Comment by dkrupp** [comment]
in the first, open perspective picture, crop out only the menu part of the picture, the rest is unnecessary
