### ISSUE TITLE
ERROR: ld.so: object 'ldlogger.so' errors while analyzing project

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/CodeCheckerEclipsePlugin#149]
ERROR: ld.so: object 'ldlogger.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'ldlogger.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'ldlogger.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'ldlogger.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'ldlogger.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'ldlogger.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'ldlogger.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/tmp/ccA0QsJt.o: In function `tooMuchDataFromStdin()':
STR31C_B.cc:(.text+0xc): warning: the `gets' function is dangerous and should not be used.

17:58:18 B

**Comment by Vodorok** [comment]
I think this could be closed as #156 enhanced environment variable management of the CDT projects. But we are not completely safe as this is only tested on the integration test phase. #172 would give us more confidence.
