### ISSUE TITLE
analyze error. unrecognized argument

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/CodeCheckerEclipsePlugin#153]
EI CERT - Ericsson: Sucessfully added CodeChecker Nature
SEI CERT - Ericsson: Sucessfully added CodeChecker Nature
usage: CodeChecker [-h] {analyze} ...
CodeChecker: error: unrecognized arguments: /home/ednikru/eclipse/workspace/.codechecker/SEI CERT - Ericsson/compilation_commands.json.javarunner1817459385742374
E-Cert-Tests: Sucessfully added CodeChecker Nature
usage: CodeChecker [-h] {analyze} ...
CodeChecker: error: unrecognized arguments: /home/ednikru/eclipse/workspace/.codechecker/E-Cert-Tests/compilation_commands.json.javarunner1818298712229653

**Comment by Vodorok** [comment]
Possible cause is when a newly configured Plugin is added, there are no checkers enabled for it, and no default group is used for the analyze.
I need to investigate more.

**Comment by Vodorok** [comment]
This was also fixed somewhere along the line, there is an empty parameter substituted into the analyze command.
