### ISSUE TITLE
Automatic test running

### ISSUE THREAD

**Issue by gyorb** [Ericsson/CodeCheckerEclipsePlugin#16]
Run unit tests automatically with Travis

**Comment by Locutus18** [comment]
Travis complete : 

sudo: required
language: java
jdk:
    - oraclejdk7
before_script:
    - sudo apt-get purge maven maven2
    - sudo apt-get install maven eclipse-platform eclipse-jdt eclipse-cdt
    - mvn --version
    - cd ../;curl http://archive.apache.org/dist/thrift/0.9.3/thrift-0.9.3.tar.gz | tar zx
    - cd thrift-0.9.3
    - ./configure --with-c_glib=yes --with-ruby=no
    - make
    - export PATH=$PATH:$PWD/compiler/cpp/
    - cd ../CodeCheckerEclipsePlugin/eclipse-plugin/
script: /usr/share/maven/bin/mvn clean package
