### ISSUE TITLE
Installation fails 

### ISSUE THREAD

**Issue by SvenHaedrich** [Ericsson/CodeCheckerEclipsePlugin#164]
My installation failed with the following message:
<pre>An error has occurred. See the log file
/home/sven/Ericsson/CodeCheckerEclipsePlugin/tests/org.codechecker.eclipse.rcp.it.tests/target/work/data/.metadata/.log.
[<font color="#729FCF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#729FCF"><b>INFO</b></font>] <b>Reactor Summary:</b>
[<font color="#729FCF"><b>INFO</b></font>] 
[<font color="#729FCF"><b>INFO</b></font>] org.codechecker.eclipse.root 1.0.0-SNAPSHOT ........ <font color="#8AE234"><b>SUCCESS</b></font> [ 10.544 s]
[<font color="#729FCF"><b>INFO</b></font>] org.codechecker.eclipse.bundles 1.0.0-SNAPSHOT ..... <font color="#8AE234"><b>SUCCESS</b></font> [  0.797 s]
[<font color="#729FCF"><b>INFO</b></font>] org.codechecker.eclipse.plugin 0.0.6-SNAPSHOT ...... <font color="#8AE234"><b>SUCCESS</b></font> [ 12.096 s]
[<font color="#729FCF"><b>INFO</b></font>] org.codechecker.eclipse.features 1.0.0-SNAPSHOT .... <font color="#8AE234"><b>SUCCESS</b></font> [  0.585 s]
[<font color="#729FCF"><b>INFO</b></font>] org.codechecker.eclipse.feature 1.0.0-SNAPSHOT ..... <font color="#8AE234"><b>SUCCESS</b></font> [  1.072 s]
[<font color="#729FCF"><b>INFO</b></font>] org.codechecker.eclipse.releng 1.0.0-SNAPSHOT ...... <font color="#8AE234"><b>SUCCESS</b></font> [  0.730 s]
[<font color="#729FCF"><b>INFO</b></font>] org.codechecker.eclipse.update 1.0.0-SNAPSHOT ...... <font color="#8AE234"><b>SUCCESS</b></font> [  3.434 s]
[<font color="#729FCF"><b>INFO</b></font>] org.codechecker.eclipse.target 1.0.0-SNAPSHOT ...... <font color="#8AE234"><b>SUCCESS</b></font> [  0.592 s]
[<font color="#729FCF"><b>INFO</b></font>] org.codechecker.eclipse.tests 1.0.0-SNAPSHOT ....... <font color="#8AE234"><b>SUCCESS</b></font> [  0.434 s]
[<font color="#729FCF"><b>INFO</b></font>] org.codechecker.eclipse.rcp.shared 1.0.0-SNAPSHOT .. <font color="#8AE234"><b>SUCCESS</b></font> [  0.854 s]
[<font color="#729FCF"><b>INFO</b></font>] org.codechecker.eclipse.rcp.unit.tests 1.0.0-SNAPSHOT <font color="#8AE234"><b>SUCCESS</b></font> [  7.579 s]
[<font color="#729FCF"><b>INFO</b></font>] org.codechecker.eclipse.rcp.it.tests 1.0.0-SNAPSHOT  <font color="#EF2929"><b>FAILURE</b></font> [ 12.011 s]
[<font color="#729FCF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#729FCF"><b>INFO</b></font>] <font color="#EF2929"><b>BUILD FAILURE</b></font>
[<font color="#729FCF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#729FCF"><b>INFO</b></font>] Total time:  03:54 min
[<font color="#729FCF"><b>INFO</b></font>] Finished at: 2019-07-02T13:18:42+02:00
[<font color="#729FCF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#EF2929"><b>ERROR</b></font>] Failed to execute goal <font color="#4E9A06">org.eclipse.tycho:tycho-surefire-plugin:1.3.0:test</font> <b>(default-test)</b> on project <font color="#06989A">org.codechecker.eclipse.rcp.it.tests</font>: <font color="#EF2929"><b>An unexpected error occured while launching the test runtime (return code 13). See log /home/sven/Ericsson/CodeCheckerEclipsePlugin/tests/org.codechecker.eclipse.rcp.it.tests/target/work/data/.metadata/.log for details.</b></font> -&gt; <b>[Help 1]</b>
[<font color="#EF2929"><b>ERROR</b></font>] 
[<font color="#EF2929"><b>ERROR</b></font>] To see the full stack trace of the errors, re-run Maven with the <b>-e</b> switch.
[<font color="#EF2929"><b>ERROR</b></font>] Re-run Maven using the <b>-X</b> switch to enable full debug logging.
[<font color="#EF2929"><b>ERROR</b></font>] 
[<font color="#EF2929"><b>ERROR</b></font>] For more information about the errors and possible solutions, please read the following articles:
[<font color="#EF2929"><b>ERROR</b></font>] <b>[Help 1]</b> http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[<font color="#EF2929"><b>ERROR</b></font>] 
[<font color="#EF2929"><b>ERROR</b></font>] After correcting the problems, you can resume the build with the command
[<font color="#EF2929"><b>ERROR</b></font>]   <b>mvn &lt;goals&gt; -rf :org.codechecker.eclipse.rcp.it.tests</b>
</pre>

The link to apache.org gave no useful information.
The log-file is attached.
[LogFile.txt](https://github.com/Ericsson/CodeCheckerEclipsePlugin/files/3349881/LogFile.txt)
Any help is welcome.

**Comment by Vodorok** [comment]
Hey, @SvenHaedrich! I'm currently investigating this issue. There is a pull request in the works that should resolve this problem.
The problem in short: Tycho mixes up java versions, that's why the integration test phase fails.
If you could test it with openjdk8, that build is definitely working.
Btw congrats for the first issue.

**Comment by SvenHaedrich** [comment]
Thank You for your fast and competent reaction. On my machine:
<pre> java -version
openjdk version &quot;11.0.3&quot; 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)
</pre>
runs OpenJDK 11. But you already new that. Anyways, I am hesitant to downgrade to OpenJDK 8. What is the expected (and maybe overly optimistic) timeframe for the pull request you mention?

**Comment by Vodorok** [comment]
Hey @SvenHaedrich! If you take a look on #167 it's building well on Travis across a variety of different jdk versions, 11 included. 
You can try that and see if it's compiles. The actual merging will be some time later because a the patch that it depends still has some problems with Travis on openjdk9, but that problem is unrelated to this.
Thanks for the bringing our attention to this issue!

**Comment by Vodorok** [comment]
Well, can you please provide a stack trace for that npe, and a link to the used eclipse?

**Comment by SvenHaedrich** [comment]
The later is easy. See here 
https://www.st.com/en/development-tools/stm32cubeide.html?ecmp=tt11319_gl_link_may2019 
. I am not so sure how to get a stack trace. Sorry.
Thank you for your attention.

------ Originalnachricht ------
Von: "Vodorok" <notifications@github.com>
An: "Ericsson/CodeCheckerEclipsePlugin" 
<CodeCheckerEclipsePlugin@noreply.github.com>
Cc: "Sven Hädrich" <svh@sevenlab.de>; "Mention" 
<mention@noreply.github.com>
Gesendet: 04.07.2019 14:39:34
Betreff: Re: [Ericsson/CodeCheckerEclipsePlugin] Installation fails 
(#164)

**Comment by SvenHaedrich** [comment]
Here is what I see on the console when I start the STM-eclipse:

<pre> /opt/st/stm32cubeide_1.0.1/stm32cubeide

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.277</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.277</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.277</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.277</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.321</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.321</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.323</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.323</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.323</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.323</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.363</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.363</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.391</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.391</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.395</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.395</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.396</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.396</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.436</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.436</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.437</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.437</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.438</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.438</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.466</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): GLib-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">17:04:07.466</font>: g_base64_encode_step: assertion &apos;in != NULL&apos; failed

(STM32CubeIDE:4930): Gtk-<font color="#FCE94F"><b>WARNING</b></font> **: <font color="#3465A4">17:04:15.016</font>: Negative content width -4 (allocation 2, extents 3x3) while allocating gadget (node progressbar, owner GtkProgressBar)

(STM32CubeIDE:4930): Gtk-<font color="#FCE94F"><b>WARNING</b></font> **: <font color="#3465A4">17:04:15.016</font>: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node trough, owner GtkProgressBar)

(STM32CubeIDE:4930): Gtk-<font color="#FCE94F"><b>WARNING</b></font> **: <font color="#3465A4">17:04:15.016</font>: Negative content width -4 (allocation 2, extents 3x3) while allocating gadget (node progressbar, owner GtkProgressBar)

(STM32CubeIDE:4930): Gtk-<font color="#FCE94F"><b>WARNING</b></font> **: <font color="#3465A4">17:04:15.016</font>: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node trough, owner GtkProgressBar)

(STM32CubeIDE:4930): Gtk-<font color="#FCE94F"><b>WARNING</b></font> **: <font color="#3465A4">17:04:15.017</font>: Negative content width -4 (allocation 2, extents 3x3) while allocating gadget (node progressbar, owner GtkProgressBar)

(STM32CubeIDE:4930): Gtk-<font color="#FCE94F"><b>WARNING</b></font> **: <font color="#3465A4">17:04:15.017</font>: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node trough, owner GtkProgressBar)

(STM32CubeIDE:4930): Gtk-<font color="#FCE94F"><b>WARNING</b></font> **: <font color="#3465A4">17:04:15.017</font>: Negative content width -4 (allocation 2, extents 3x3) while allocating gadget (node progressbar, owner GtkProgressBar)

(STM32CubeIDE:4930): Gtk-<font color="#FCE94F"><b>WARNING</b></font> **: <font color="#3465A4">17:04:15.017</font>: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node trough, owner GtkProgressBar)
org.osgi.service.prefs.BackingStoreException: Exception occurred while saving project preferences: /Gateway/.settings/org.codechecker.eclipse.plugin.CodeCheckerNature.prefs.
	at org.eclipse.core.internal.resources.ProjectPreferences.save(ProjectPreferences.java:679)
	at org.eclipse.core.internal.preferences.EclipsePreferences.internalFlush(EclipsePreferences.java:431)
	at org.eclipse.core.internal.resources.ProjectPreferences.flush(ProjectPreferences.java:371)
	at org.codechecker.eclipse.plugin.config.CcConfiguration.validate(CcConfiguration.java:77)
	at org.codechecker.eclipse.plugin.config.CcConfiguration.load(CcConfiguration.java:43)
	at org.codechecker.eclipse.plugin.config.CcConfiguration.&lt;init&gt;(CcConfiguration.java:35)
	at org.codechecker.eclipse.plugin.config.project.CodeCheckerProject.&lt;init&gt;(CodeCheckerProject.java:68)
	at org.codechecker.eclipse.plugin.init.StartupJob.projectOpened(StartupJob.java:124)
	at org.codechecker.eclipse.plugin.init.StartupJob.runInUIThread(StartupJob.java:93)
	at org.codechecker.eclipse.plugin.init.StartupJob.run(StartupJob.java:63)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

</pre>
