### ISSUE TITLE
codechecker configuration should be moved to global configuration

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/CodeCheckerEclipsePlugin#24]
Currently codechecker configuration is in the project specific settings.
However codechecker paths are not project specific.

Move the configuration options under Window/Preferences/CodeChecker

**Comment by dutow** [comment]
Instead of just moving the configuration into the global preferences, it would be better to follow the usual eclipse configuration layers with three levels (global, workspace, project), it adds little extra to the implementation complexity.

**Comment by dkrupp** [comment]
You are right. anyway, when we will add checker configuration, the user might want to customize it per project

**Comment by whisperity** [comment]
It seems I've duplicated this issue in #62.
