### ISSUE TITLE
ReportList all and current file seclude

### ISSUE THREAD

**Issue by Locutus18** [Ericsson/CodeCheckerEclipsePlugin#29]
We should create TWO ReportList views

* one should list all bugs found *in the project*
* the other should list the ones in the *currently active file*

The two should be next to each other.

**Comment by whisperity** [comment]
An extra suggestion would be to colourise `bugPathItems` that is referring the current file opened. (So, e.g. the user can see if viewing the project report that the current file is referenced in another bug.)

For the **currently open file's ReportList**, we could programmatically remove the CheckerGroup/CheckerName layout by having the `CheckerName`s as first level entries in the tree. I don't think there's that much of a neccessity to group checkers for one particular file.

**Comment by dkrupp** [comment]
I agree that we don't need to branch the tree at checker package names such as: 
|-deadcode   
  |--deadcode.DeadStores

it could be simply
-deadcode.DeadStores
