### ISSUE TITLE
Show all the bugs in the current project

### ISSUE THREAD

**Issue by bobszi** [Ericsson/CodeCheckerEclipsePlugin#4]
Most probably this will include redesigning the ReportList and BugPathList viewparts.

**Comment by dutow** [comment]
This is possible with the current UI: you can delink the reportlist from the editor panel, and I think the default query does exactly this, but you can also create (and save/load) filters too. 

Maybe the UI could be easier to use, or we could allow multiple reportlist and buglists windows to be open.

**Comment by dkrupp** [comment]
I propose to add 2 icons to the report list to switch between bugs in current file and all bugs.

**Comment by dutow** [comment]
A better solution would be to allow multiple reportlist windows to be open, and add two windows to the codechecker perspective by default (current file and entire project). That way users could open even more windows and customize their locations separately.

The code supports this workflow, only a few UI elements are missing for it.

**Comment by gyorb** [comment]
I would suggest not to use too many windows and keep the UI as simple as possible. Too many windows might take too much screen space.

**Comment by dkrupp** [comment]
One more window takes away more space from workbench. The main question is whether the user wants to see the file local and global bug list at the same time. I would prefer a single window view

**Comment by dutow** [comment]
How can he see it with just a single window at the same time? You suggested a toggle, which means he can choose which one to display, one at a time.

the eclipse platform also allows the users to place multiple windows into the same slot and switch between them using a tab control. So the multiple window approach supports both workflows. I think most users would prefer a more flexible system which they can customize according to their preferences.

Another example would be to add a separate (third) window which for example only shows the severe reports.

**Comment by dkrupp** [comment]
well i think the user does not want see the two list at the same time. that's why i proposed switchable views. But tabbed views in a single windows is also fine

**Comment by dutow** [comment]
My original idea behind the multiple window feature was based on related bugs: if I check the report list, and see that there are several different issues which are probably related, I might want to open each in its own window so I can easily switch between them.

Another use case is when I have to go into a file not shown in the bug path to fix the bug / check some information related to it. In this case, I might want a window following the current file (to show the bugs in the newly opened editor), but also keep the issue I'm currently fixing open.
