### ISSUE TITLE
console logging

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/CodeCheckerEclipsePlugin#58]
Log to the console the following events:
1. CodeChecker command when the server is started.
2. CodeChecker command when the checking is started.
3. The event when the checking is finished
4. The event when the results are queried from the server (and updated in the GUI).

**Comment by whisperity** [comment]
Just my two cents but shouldn't we also log the event when a checking has been enqueued on a certain project's queue thread? That is currently only logged as `DEBUG`.

**Comment by dkrupp** [comment]
agreed
