### ISSUE TITLE
bugs in the current project list not shown correctly

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/CodeCheckerEclipsePlugin#74]
When a file is open in the editor part (and you have at least 2 open projects in eclipse) and you press rebuild all project, in the current project view, the bug list of the lastly built project is shown (instead of the current project)

**Comment by Locutus18** [comment]
I see, but what happens if there are two projects added to Eclipse and one project's file is open; and you build the OTHER project while you wish to see in `Current Project` view not the results of the open file but the actual current (last built) project?
